name: eavzappl
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_picker: ^1.1.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_database: ^10.4.9
  firebase_messaging: ^14.7.19
  cloud_firestore: ^4.15.8
  intl_phone_field: ^3.2.0
  intl: ^0.19.0
  flutter_image_slider:
  image_cropper: ^9.1.0
  path: ^1.9.0
  firebase_app_check: ^0.2.2
  url_launcher: ^6.3.0
  http: ^1.6.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  equatable:
  json_annotation: ^4.9.0
  logger: ^2.3.0
  transparent_image: ^2.0.1
  image: ^4.5.4
  path_provider: ^2.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/splashScreen/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/eavzappl_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/eavzappl_logo.png"
